# Generated by Django 3.0.3 on 2020-06-10 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name', max_length=150)),
                ('emails', models.EmailField(help_text='Enter Email', max_length=250)),
                ('message', models.TextField(max_length=2000)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
